### PR TITLE
2022-01-25 - Use SSL for Websocket & Log Server connections

### PR DESCRIPTION
**Pull request by knowuh**
### Use SSL for Websocket & Log Server connections

Otherwise we get mixed-content security warnings when the application loads over HTTP.

### CODE REVIEW

**Review by mklewandowski — COMMENTED** [review]
👍 So far this is looking good!  I think we should do a little more testing of local and deployed versions before merging.  I would like to ensure that Nathan has a chance to test and I would like to make sure that my local version still behaves as expected.  Otherwise, this is looking good!

**Review by mklewandowski — APPROVED** [review]
👍 Testing shows this works in both WebGL and HL2 builds.

**Comment by kswenson** [comment]
> Testing shows this works in both WebGL and HL2 builds.

Sort of makes you wonder why it wasn't done before. 🤔

**Comment by mklewandowski** [comment]
> > Testing shows this works in both WebGL and HL2 builds.
> 
> Sort of makes you wonder why it wasn't done before. 🤔

Not sure.  I couldn't find any comments or discussion on the topic.  It could have something to do with ease in setting up local testing or it could be related to one of the devices that we no longer support (Oculus Rift, HL1).

**Pull request merged**
